### ISSUE TITLE
Extreme Issue

### ISSUE THREAD

**Issue by murasaki96** [Gamerbolts/bca#2]
Extreme issue
.  
Minecraft comes alive. 

Minecraft is currently unplayable to me.  My person will have to be reset on the server to get back to spawn. Its an area crash. I was flying and was coming up on a regular mine-craft village next to a lost cities.  Every time i load in i immediately crash off the server. 

https://paste.dimdev.org/rupugoxasu.mccrash

**Comment by Gamerbolts** [comment]
Removed MCA. Is not being updated anymore
